[minor] Add json validator (#26)
* add a todo
it would be nice if we could run without a server at all in the browser.

* add a validation script

* update validation script to be more verbose about errors

* add validator to the composer.json

* add good and bad manifest.json files

* script the creation of the level json files

* add a test of the validator

* remove the data directory

* move the manifest.json fixture files into a higher directory

* add autotag action

* fix the path to the scripts

* remove setup scripts and just create the files

* add the valid json level files

* update the validation check

* maybe fix validation check?

* add some debugging

* remove echo to stderr for success

* remove ls

* add echoes

* update validation failing tests

* update json validation

* update manifest.json validation to catch problems

* remove the else clause

* maybe better error handling when validating files

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -17,4 +17,42 @@ jobs:
           composer install
       - name: Lint
         run: composer lint
-        
+      - name: Test validator
+        run: |
+          # Initialize an empty string to collect errors
+          VALIDATION_ERRORS=""
+          echo "Testing good files..."
+          # Loop through all files in the good fixtures directory and copy them to the src/data directory
+          for file in ${{ github.workspace }}/.github/workflows/fixtures/good/*.json; do
+            echo "Copying $file..."
+            cp "$file" "${{ github.workspace }}/src/data/"
+          done
+
+          # Validate good files, expecting success
+          if ! composer validate-files; then
+            VALIDATION_ERRORS+="Validation failed for good input. "
+          fi
+          
+          # Clean up after testing with valid files
+          composer clean-files
+          
+          echo "Testing bad files..."
+          # Setup for invalid files
+          for file in ${{ github.workspace }}/.github/workflows/fixtures/bad/*.json; do
+            echo "Copying $file..."
+            cp "$file" "${{ github.workspace }}/src/data/"
+          done
+
+          # Validate bad files, expecting failure
+          if composer validate-files; then
+            # If the validation unexpectedly succeeds, this is incorrect for bad input
+            VALIDATION_ERRORS+="Validation did not fail as expected for bad input. "
+          fi
+
+          # Check if there were any validation errors
+          if [ -n "$VALIDATION_ERRORS" ]; then
+            echo "Errors during validation: $VALIDATION_ERRORS"
+            exit 1
+          else
+            echo "All validations passed successfully."
+          fi
