add a test of the validator

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -17,4 +17,36 @@ jobs:
           composer install
       - name: Lint
         run: composer lint
-        
+      - name: Test validator
+        env:
+          GITHUB_WORKSPACE: ${{ github.workspace }}
+        run: |
+          # Initialize an empty string to collect errors
+          VALIDATION_ERRORS=""
+          
+          # Setup for valid files
+          cp $GITHUB_WORKSPACE/.github/workflows/fixtures/good/manifest.json $GITHUB_WORKSPACE/src/data/manifest.json
+          bash $GITHUB_WORKSPACE/.github/workflows/create-good-files.sh
+          # Validate good files, expecting success
+          if ! composer validate-files; then
+            VALIDATION_ERRORS+="Validation failed for good input. "
+          fi
+          
+          # Clean up after testing with valid files
+          composer clean-files
+          
+          # Setup for invalid files
+          cp $GITHUB_WORKSPACE/.github/workflows/fixtures/bad/manifest.json $GITHUB_WORKSPACE/src/data/manifest.json
+          bash $GITHUB_WORKSPACE/.github/workflows/create-bad-files.sh
+          # Validate bad files, expecting failure
+          if composer validate-files; then
+            VALIDATION_ERRORS+="Validation did not fail as expected for bad input. "
+          fi
+          
+          # Check if there were any validation errors
+          if [ -n "$VALIDATION_ERRORS" ]; then
+            echo "Errors during validation: $VALIDATION_ERRORS"
+            exit 1
+          else
+            echo "All validations passed successfully."
+          fi
